### ISSUE TITLE
ClickHouse as destination

### ISSUE THREAD

**Issue by vklimontovich** [ksensehq/eventnative#29]
Add support of ClickHouse as a destination.

**Comment by aslubsky** [comment]
Hey, thanks for great tool! Is there any ETA for this feature?

**Comment by vklimontovich** [comment]
Hey, thank you very much! 

@xtreding is working very hard now to roll out CH integration next week! Stay tuned

**Comment by xtreding** [comment]
Hi @aslubsky!
We've added ClickHouse support. For more information visit https://docs.eventnative.dev/configuration/clickhouse-destination

**Comment by aslubsky** [comment]
Thanks guys, you are awesome ))
