### ISSUE TITLE
Destination: Postgres | SSL

### ISSUE THREAD

**Issue by PaulFish-Radius** [ksensehq/eventnative#42]
Hi! 👋 

Received this error when attempted to spin up EventNative using a posgres db on my localhost. 
Does postgres require SSL for the application to work? I'd like to avoid configuring SSL on my local instance. 

`api_1      | 2020/08/17 03:59:02 Error initializing postgres_ksense destination of type postgres: pq: SSL is not enabled on the server
api_1      | 2020/08/17 03:59:02 There is no configured event batch destinations`

Thank you for the information.

**Comment by xtreding** [comment]
Hi @PaulFish-Radius! I've pushed a new version(1.2.2) that supports configurable Postgres connection parameters.
In your case for avoiding configuring SSL, please provide 
`
  datasource.parameters.sslmode: disable      
 `
For more information, please visit:
https://app.gitbook.com/@eventnative/s/eventnative/configuration
https://www.postgresql.org/docs/9.1/libpq-connect.html

**Comment by PaulFish-Radius** [comment]
@xtreding that was so fast and connection worked perfectly. 👌 Kind of you.
