### ISSUE TITLE
S3 as destination: flat file support

### ISSUE THREAD

**Issue by jdotjdot** [ksensehq/eventnative#44]
Is there a way to get EventNative to buffer/ship tracked line items to flat files somewhere like S3? I would imagine you already have to do this anyway for loading into Redshift, so the goal would be to be able to keep the original buffered staging files, but as the final destination.

**Comment by vklimontovich** [comment]
Hi @jdotjdot !

We not sure we can support files on local drive, but S3 as a destination definitely something we can do. You're right, it's already done internally

**Comment by jdotjdot** [comment]
Looking for remote, definitely not local drives.  But should ideally be generic block storage, could start with anything that has an S3-compatible API.

**Comment by xtreding** [comment]
Hi @jdotjdot!
Thank you for the issue! I've pushed a new version(1.2.5) that supports S3 destination.
For more information, please visit:
https://app.gitbook.com/@eventnative/s/eventnative/configuration

**Comment by jdotjdot** [comment]
Thanks! Seems like the link doesn't work?

**Comment by xtreding** [comment]
@jdotjdot  Sorry, the new one: https://docs.eventnative.dev/configuration
