### ISSUE TITLE
Java SDK

### ISSUE THREAD

**Issue by vklimontovich** [ksensehq/eventnative#45]
Should be based on an API (https://docs.eventnative.dev/api) and published to maven repo

**Comment by akhtyamovrr** [comment]
https://github.com/ksensehq/eventnative-java-sdk - SDK repository
https://mvnrepository.com/artifact/org.eventnative/eventnative - maven release
https://github.com/ksensehq/eventnative-java-sdk/wiki/Maven-release-flow - release flow description
