### ISSUE TITLE
JS Tracker improvements & dependencies fix

### ISSUE THREAD

**Issue by ElKornacio** [ksensehq/eventnative#51]
I've noticed several small flaws in the current setup of the npm module (./web/):

- Dependencies should be moved to devDependencies as they aren't required in the production code.
- It would be nice to have file changes watcher with auto recompilation
- Usage of scripts like buildjs.sh seems to be not a very good practice, popular projects more often use npm scripts (e.g. https://github.com/mobxjs/mobx/blob/mobx6/package.json)
- I would suggest using port choosing utility from react-dev-utils/WebpackDevServerUtils (as 80 port is often busy on devs' machines)
- And it would be nice to have some health checks after building a new version of JS Tracker

**Comment by vklimontovich** [comment]
Thank you very much for pull request! Closing
