### ISSUE TITLE
Docker image contains unnecessary layouts and cached files

### ISSUE THREAD

**Issue by iaroslavscript** [ksensehq/eventnative#83]
Hi!
After reading your blog at habr.com and experimenting with EventNative I've found that docker image contains unnecessary layers which makes it so huge.
Please see my pull request #82

**Comment by xtreding** [comment]
Hi @iaroslavscript! Thank you! I've merged it.

**Comment by iaroslavscript** [comment]
Thanks!
By the way I highly recommend to move **app/res/** and **logs/events/** away from user home directory.
Because currently these volume paths depend on user name.

I'd prefer something like this
```
docker run -p <local_port>:8001 \
  -v /{CONFIG_DIR}/:/app/res/ \
  -v /{LOG_DIR}/:/app/logs/events/ \
  ksense/eventnative:latest
```
instead of
```
docker run -p <local_port>:8001 \
  -v /{CONFIG_DIR}/:/home/eventnative/app/res/ \
  -v /{LOG_DIR}/:/home/eventnative/logs/events/ \
  ksense/eventnative:latest
```
